// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Tue Mar 14 16:35:35 2023

binarytobcd binarytobcd_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.binary_value(binary_value_sig) ,	// input [7:0] binary_value_sig
	.one(one_sig) ,	// output [3:0] one_sig
	.ten(ten_sig) ,	// output [3:0] ten_sig
	.hundred(hundred_sig) 	// output [3:0] hundred_sig
);

