// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Mon Mar 13 15:43:07 2023

newsegmentdecoder7 newsegmentdecoder7_inst
(
	.inputA(inputA_sig) ,	// input  inputA_sig
	.inputB(inputB_sig) ,	// input  inputB_sig
	.inputC(inputC_sig) ,	// input  inputC_sig
	.inputD(inputD_sig) ,	// input  inputD_sig
	.a(a_sig) ,	// output  a_sig
	.b(b_sig) ,	// output  b_sig
	.c(c_sig) ,	// output  c_sig
	.d(d_sig) ,	// output  d_sig
	.e(e_sig) ,	// output  e_sig
	.f(f_sig) ,	// output  f_sig
	.g(g_sig) 	// output  g_sig
);

